User Menu 2.0
IONOS-Productivity/nc-ionos-theme pull request #10
Opened 2024-08-14 08:59 UTC by bromiesTM

2024-08-15 07:01 UTC, bromiesTM commented on IONOS/src/components/Icon.svelte
> +		height={size * 26}
todo: seems like the size is incorrect
According to the mockup, the width and height should have an equal ratio

2024-08-15 07:07 UTC, bromiesTM commented on core/templates/layout.user.php
> +							<?php p($_['user_displayname']); ?>
todo: unstyled username is the first thing visible during page load 

same with `OCP\IUser::getDisplayName`

2024-08-15 07:10 UTC, bromiesTM commented on core/css/server.css
> +	--text-color: #001b41;
suggestion: we should think about removing brand colours from the server.css
sth. like this https://github.com/IONOS-Productivity/nc-ionos-theme/commit/18317b7118cf3552a90d0f7f9fd4eefaa409d222

2024-08-20 09:45 UTC, fracado requested changes
Review done.

2024-08-20 10:56 UTC, fracado commented on IONOS/Containerfile
> +# SPDX-FileCopyrightText: 2024 STRATO AG
I'm not sure if this complies with the [license header guidelines](https://docs.nextcloud.com/server/latest/developer_manual/getting_started/codingguidelines.html#license-headers)... :thinking: 
@thlehmann-ionos What do you think?

2024-08-20 11:47 UTC, thlehmann-ionos commented on IONOS/Containerfile
> +# SPDX-FileCopyrightText: 2024 STRATO AG
They even have an example with a company name.

2024-08-20 11:54 UTC, fracado commented on IONOS/Containerfile
> +# SPDX-FileCopyrightText: 2024 STRATO AG
I know... I wasn't sure if in that case we also need something like the "and contributors" part or not. Or if we have to add our names to that mentioned AUTHORS.md file or not?

2024-08-20 11:58 UTC, thlehmann-ionos commented on IONOS/Containerfile
> +# SPDX-FileCopyrightText: 2024 STRATO AG
> ... if the author is being paid by their employer to create a work, the employer is often the copyright holder.

Source: https://reuse.software/faq/#copyright-holder-author

Referring to the [specification][spec] I read that as:

```
SPDX-FileCopyrightText: 2024 STRATO AG
SPDX-License-Identifier: AGPL-3.0-or-later
SPDX-FileContributor: Kai Henseler <kai.henseler@strato.de>
```

[spec]: https://spdx.github.io/spdx-spec/v2.3/file-tags/

2024-08-20 12:10 UTC, fracado commented on IONOS/Containerfile
> +# SPDX-FileCopyrightText: 2024 STRATO AG
Ah... yeah, let's do it like that, if you agree @bromiesTM. Thanks @thlehmann-ionos! :slightly_smiling_face:

2024-08-20 12:28 UTC, bromiesTM commented on IONOS/Containerfile
> +# SPDX-FileCopyrightText: 2024 STRATO AG
Well then you should add yourself too as I copied your work 🤔

2024-08-20 12:57 UTC, bromiesTM commented on IONOS/Containerfile
> +# SPDX-FileCopyrightText: 2024 STRATO AG
[Done](https://github.com/IONOS-Productivity/nc-ionos-theme/compare/ea0d20ab61dfba883d80c8ebc6447234b9f76ef3..6fee4f0e69406efa43bf715d5ab72a7c9acf94cb)

2024-08-20 13:46 UTC, fracado approved these changes

2024-08-20 13:46 UTC, fracado approved these changes
review OK

2024-08-20 13:49 UTC, merged