hide file settings link
IONOS-Productivity/nc-ionos-theme pull request #14
Opened 2024-08-26 10:42 UTC by fracado

2024-08-26 12:54 UTC, matsaur reviewed
For me this solution is a little bit too "generic". What do you think about using data attribute? (data-cy-files-navigation-settings-button)

2024-08-26 15:03 UTC, bromiesTM requested changes
Review OK with Minor amends

2024-08-26 15:03 UTC, bromiesTM commented on core/css/server.css
> +
suggestion(non-blocking): we should add some kind of comment on why we are doing this. We probably won't remember at some point in the future

2024-08-26 15:03 UTC, bromiesTM commented on core/css/server.css
> +.app-navigation .app-navigation-entry__settings li:nth-child(2) {
I second that → https://github.com/IONOS-Productivity/nc-ionos-theme/pull/14#pullrequestreview-2260612557

2024-08-26 15:03 UTC, bromiesTM commented on core/css/server.css
> +	display: none;
question: did you check if we are able to set the default values of the settings via configs etc?

2024-08-27 07:04 UTC, fracado commented on core/css/server.css
> +	display: none;
I thought, as the settings aren't affected by this change, the default settings remain as we want them. And therefore nothing needs to be done there. But please correct me if I'm wrong.

2024-08-27 07:51 UTC, fracado commented on core/css/server.css
> +
done with 6479336812e5ab993c901470f787c779ed05e7e0

2024-08-27 07:51 UTC, fracado commented on core/css/server.css
> +.app-navigation .app-navigation-entry__settings li:nth-child(2) {
done with 6479336812e5ab993c901470f787c779ed05e7e0

2024-08-27 08:30 UTC, bromiesTM commented on core/css/server.css
> +	display: none;
I double-checked, and it seems like hidden files should be enabled by default, but currently isn't.

2024-08-28 10:16 UTC, merged