Header for public pages
IONOS-Productivity/nc-ionos-theme pull request #9
Opened 2024-08-12 08:13 UTC by bromiesTM

2024-08-12 14:23 UTC, printminion-co requested changes
review ok if requested changes are addressed

2024-08-12 14:23 UTC, printminion-co commented on core/css/server.css
> +	}
```suggestion
```
* looks better without this lines

2024-08-12 14:23 UTC, printminion-co commented on core/templates/custom/ionos_header.php
> +</header>
new line warning is seen here

2024-08-12 15:33 UTC, thlehmann-ionos commented on core/templates/layout.public.php
> +	<?php print_unescaped($this->inc('custom/ionos_header')); ?>
Technically makes no difference since both print/echo:

* https://github.com/nextcloud/server/blame/f2e6abadbfd55e2686c1b4c84c45831420f75c91/lib/private/legacy/OC_Template.php#L186
* https://github.com/nextcloud/server/blame/f2e6abadbfd55e2686c1b4c84c45831420f75c91/lib/private/legacy/template/functions.php#L118

`print_unescaped` seems wider used and "newer" but also legacy nevertheless.

```
[12.08. 17:30 ionos-dev @0b40e379 nextcloud-server]$ grep -R 'print_unescaped' lib/ core/ | wc -l
61
[12.08. 17:30 ionos-dev @0b40e379 nextcloud-server]$ grep -R '[^a-zA-Z0-9_]echo ' lib/ core/ | wc -l
40
```

Note: `print_unescaped` expresses its potential danger better in it's name.

2024-08-13 07:07 UTC, thlehmann-ionos commented
Is it possible that this introduced extra space between the global navigation (header) and content?
![image](https://github.com/user-attachments/assets/fe91898d-3c03-4553-88ec-26a7637be904)

2024-08-13 07:21 UTC, bromiesTM commented
> Is it possible that this introduced extra space between the global navigation (header) and content? ![image](https://private-user-images.githubusercontent.com/147605810/357309035-fe91898d-3c03-4553-88ec-26a7637be904.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzM5NTUsIm5iZiI6MTcyMzUzMzY1NSwicGF0aCI6Ii8xNDc2MDU4MTAvMzU3MzA5MDM1LWZlOTE4OThkLTNjMDMtNDU1My04OGVjLTI2YTc2MzdiZTkwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QwNzIwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMWQ3OTEwNmQ4ZGQ2YzE1ZjgzYTkxZDlmZmFjOWRlOWIwZTRmNGU0ZmYzOGE4ZTM3YzI5ZjUxZTliZDA5MjJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.igAMcDmYncoZCjdyRoC1ioyR2fQwXRUKAQxIE24w13s)

It did, i fixed it [here](https://github.com/IONOS-Productivity/nc-ionos-theme/compare/fafc8c1b14febe62bf2fd9f2f548e9a29b59553a..3c89beeb855616e50a7909da00ca727ddfd4a435)

2024-08-13 14:03 UTC, printminion-co approved these changes
review ok

2024-08-14 07:16 UTC, merged